# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  #    ------------------ VM 1 - Testing ( UBUNTU) ------------------------

  config.vm.define "Testing" do |vmHost1|
    vmHost1.vm.box = "ubuntu/jammy64"
    vmHost1.vm.hostname = "vmHost1"
    vmHost1.vm.network "private_network", :name => '', ip: "192.168.56.5"

    # Comparto la carpeta del host donde estoy parado contra la vm
    vmHost1.vm.synced_folder 'compartido_Host1/', '/home/vagrant/compartido', 
      owner: 'vagrant', group: 'vagrant' 

      # Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
      vmHost1.ssh.insert_key = true
      # Agrego un nuevo disco 
      vmHost1.vm.disk :disk, size: "5GB", name: "#{vmHost1.vm.hostname}_extra_storage"
      vmHost1.vm.disk :disk, size: "3GB", name: "#{vmHost1.vm.hostname}_extra_storage2"
      vmHost1.vm.disk :disk, size: "2GB", name: "#{vmHost1.vm.hostname}_extra_storage3"
      vmHost1.vm.disk :disk, size: "1GB", name: "#{vmHost1.vm.hostname}_extra_storage4"

      vmHost1.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "vmHost1"
        vb.cpus = 1
        vb.linked_clone = true
        # Seteo controladora Grafica
        vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']      
      end    
      # Puedo Ejecutar un script que esta en un archivo
      vmHost1.vm.provision "shell", path: "script_Enable_ssh_password.sh"
      vmHost1.vm.provision "shell", privileged: false, path: "script_Fix_history.sh"
      vmHost1.vm.provision "shell", path: "instala_paquetes.sh"
      vmHost1.vm.provision "shell", privileged: false, inline: <<-SHELL
      # Los comandos aca se ejecutan como vagrant

      echo "192.168.56.5  vmHost1" | sudo tee -a /etc/hosts
      echo "192.168.56.6  vmHost2" | sudo tee -a /etc/hosts
  
      mkdir -p /home/vagrant/repogit
      cd /home/vagrant/repogit
      git clone https://github.com/upszot/UTN-FRA_SO_TP-Integral.git
      git clone https://github.com/LELautaroEmilioLotoski/TP_AySO_Integral_-314-.git
      

    SHELL
    end
    
    #    ------------------ VM 2 - Produccion ( Fedora) ------------------------
    config.vm.define "Produccion" do |vmHost2|
      #vmHost2.vm.box = "generic/rhel9"
      vmHost2.vm.box = "ubuntu/jammy64"
      #vmHost2.vm.box = "generic/fedora40"
      #vmHost2.vm.box = "fedora/39-cloud-base"
      vmHost2.vm.hostname = "vmHost2"
      vmHost2.vm.network "private_network", :name => '', ip: "192.168.56.6"
      # Agrego Discos a la VM de Produccion.
      vmHost2.vm.disk :disk, size: "5GB", name: "#{vmHost2.vm.hostname}_extra_storage"
      vmHost2.vm.disk :disk, size: "3GB", name: "#{vmHost2.vm.hostname}_extra_storage2"
      vmHost2.vm.disk :disk, size: "2GB", name: "#{vmHost2.vm.hostname}_extra_storage3"
      vmHost2.vm.disk :disk, size: "1GB", name: "#{vmHost2.vm.hostname}_extra_storage4"
      
      # Comparto la carpeta del host donde estoy parado contra la vm
      vmHost2.vm.synced_folder 'compartido_Host2/', '/home/vagrant/compartido'
  
    # Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
    vmHost2.ssh.insert_key = true
    vmHost2.vm.provider "virtualbox" do |vb2|
      vb2.memory = "1024"
      vb2.name = "vmHost2"
      vb2.cpus = 1
      vb2.linked_clone = true
      # Seteo controladora Grafica
      vb2.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end
    
    #Agregamos comando para el cruce de cuentas
    vmHost2.vm.provision "shell", privileged: false, inline: <<-SHELL

      echo "192.168.56.5  vmHost1" | sudo tee -a /etc/hosts
      echo "192.168.56.6  vmHost2" | sudo tee -a /etc/hosts

    SHELL
    
    # Puedo Ejecutar un script que esta en un archivo
    vmHost2.vm.provision "shell", path: "script_Enable_ssh_password.sh"
    vmHost2.vm.provision "shell", privileged: false, path: "script_Fix_history.sh"

    # Provisión para instalar
    #vmHost2.vm.provision "shell", inline: <<-SHELL
      #sudo dnf install -y tree
     # sudo dnf install -y git
    #SHELL
  end
end
